;/*FB_PKG_DELIM*/

__d("useShallowEqualState",["react","react-compiler-runtime","shallowEqual"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||d("react");b.useCallback;var i=b.useState;function a(a){var b=d("react-compiler-runtime").c(3);a=i(a);var e=a[0],f=a[1];b[0]===Symbol["for"]("react.memo_cache_sentinel")?(a=function(a){if(typeof a==="function"){var b=a;return f(function(a){var d=b(a);return c("shallowEqual")(a,d)?a:d})}return f(function(b){return c("shallowEqual")(b,a)?b:a})},b[0]=a):a=b[0];a=a;b[1]!==e?(a=[e,a],b[1]=e,b[2]=a):a=b[2];return a}g["default"]=a}),98);
__d("BasePulseEffect.react",["BasePulseEffectBase.react","react","react-compiler-runtime","useMergeRefs","useMutationObserver","useResizeObserver","useShallowEqualState","useVisibilityObserver"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));b=h;b.useCallback;var j=b.useRef,k=b.useState;function a(a){var b=d("react-compiler-runtime").c(24),e=a.children,f=a.disabled,g=a.pulseColor_DEPRECATED;a=a.xstyle;f=f===void 0?!1:f;var h=j(null),l=k(null),m=l[0],n=l[1];l=k(null);var o=l[0],p=l[1];l=c("useShallowEqualState")(null);var q=l[0],r=l[1];l=k(!1);var s=l[0],t=l[1];b[0]!==s?(l=function(a){a=a.hiddenReason;s&&a!=="COMPONENT_UNMOUNTED"&&t(!1)},b[0]=s,b[1]=l):l=b[1];var u;b[2]===Symbol["for"]("react.memo_cache_sentinel")?(u=function(){return t(!0)},b[2]=u):u=b[2];b[3]!==l?(u={onHidden:l,onVisible:u},b[3]=l,b[4]=u):u=b[4];l=c("useVisibilityObserver")(u);b[5]!==r?(u=function(a){if(a!=null){a=window.getComputedStyle(a);var b=a.borderBottomLeftRadius,c=a.borderBottomRightRadius,d=a.borderTopLeftRadius;a=a.borderTopRightRadius;r({borderBottomLeftRadius:b,borderBottomRightRadius:c,borderTopLeftRadius:d,borderTopRightRadius:a})}},b[5]=r,b[6]=u):u=b[6];var v=u;b[7]!==r?(u=function(a,b){p(a.height);n(a.width);a=window.getComputedStyle(b);b=a.borderBottomLeftRadius;var c=a.borderBottomRightRadius,d=a.borderTopLeftRadius;a=a.borderTopRightRadius;r({borderBottomLeftRadius:b,borderBottomRightRadius:c,borderTopLeftRadius:d,borderTopRightRadius:a})},b[7]=r,b[8]=u):u=b[8];u=c("useResizeObserver")(u);var w;b[9]!==v?(w=function(){return v(h.current)},b[9]=v,b[10]=w):w=b[10];var x;b[11]===Symbol["for"]("react.memo_cache_sentinel")?(x={attributeFilter:["style","class"],attributes:!0},b[11]=x):x=b[11];w=c("useMutationObserver")(w,x);x=c("useMergeRefs")(h,l,v,u,w);b[12]!==e||b[13]!==x?(l=e(x),b[12]=e,b[13]=x,b[14]=l):l=b[14];b[15]!==o||b[16]!==q||b[17]!==m||b[18]!==f||b[19]!==g||b[20]!==l||b[21]!==s||b[22]!==a?(u=i.jsx(c("BasePulseEffectBase.react"),{disabled:f,height:o,pulseColor:g,radii:q,visible:s,width:m,xstyle:a,children:l}),b[15]=o,b[16]=q,b[17]=m,b[18]=f,b[19]=g,b[20]=l,b[21]=s,b[22]=a,b[23]=u):u=b[23];return u}g["default"]=a}),98);
__d("BizWebHomeRedirectExperiments.entrypointutils",["QE2Logger","qex"],(function(a,b,c,d,e,f,g){"use strict";function a(a){a===void 0&&(a=!1);a&&d("QE2Logger").logExposureForActingAccountCritical("bizweb_comet_home_redirect_experiments_universe");return(a=c("qex")._("2282"))!=null?a:!1}function b(a){a===void 0&&(a=!1);a&&d("QE2Logger").logExposureForActingAccountCritical("bizweb_comet_home_redirect_experiments_universe");return(a=c("qex")._("2283"))!=null?a:!1}g.getBizWebHomeRedirectFromFBPPlusSettingsMenuEntrypointutils=a;g.getBizWebHomeRedirectFromFBPPlusLeftNavEntrypointutils=b}),98);
__d("CometProfileTypeDialogRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9863258203732747"}),null);
__d("CometProfileTypeDialogRootQuery$Parameters",["CometProfileTypeDialogRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("CometProfileTypeDialogRootQuery_facebookRelayOperation"),metadata:{},name:"CometProfileTypeDialogRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometProfileTypeDialog.entrypoint",["CometProfileTypeDialogRootQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(){return{queries:{root:{parameters:b("CometProfileTypeDialogRootQuery$Parameters"),variables:{scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("CometProfileTypeDialog.react").__setRef("CometProfileTypeDialog.entrypoint")};g["default"]=a}),98);
__d("FDSAccountSwitcherFilled16PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("622240"),16);b=a;g["default"]=b}),98);
__d("FDSArrowDiagonalRightUpFilled16Icon",["cr:14398"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14398")}),98);
__d("FDSArrowDiagonalRightUpFilled16PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("620418"),16);b=a;g["default"]=b}),98);
__d("FDSPlusCircleFilled20Icon",["cr:14063"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14063")}),98);
__d("FDSPlusCircleFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("487087"),20);b=a;g["default"]=b}),98);
__d("FDSPulseEffect.react",["BasePulseEffect.react","FDSPulseEffectBase.react","react","react-compiler-runtime"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){var b=d("react-compiler-runtime").c(2),e;b[0]!==a?(e=i.jsx(c("BasePulseEffect.react"),babelHelpers["extends"]({},a,{pulseColor_DEPRECATED:d("FDSPulseEffectBase.react").FDS_PULSE_COLORS.primary})),b[0]=a,b[1]=e):e=b[1];return e}g["default"]=a}),98);
__d("FDSQuestionCircleFilled20Icon",["cr:14075"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:14075")}),98);
__d("FDSQuestionCircleFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("496951"),20);b=a;g["default"]=b}),98);
__d("FDSTranslateFilled20Icon",["cr:15801"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=b("cr:15801")}),98);
__d("FDSTranslateFilled20PNGIcon.react",["ix","fbicon"],(function(a,b,c,d,e,f,g,h){"use strict";a=d("fbicon")._(h("1107405"),20);b=a;g["default"]=b}),98);
__d("useCometTypeaheadScrollableViewListStrategy",["CometScrollableArea.react","react","react-compiler-runtime","useCometInternalTypeaheadState","useCometTypeaheadKeyboardForScrollableArea","useCometTypeaheadViewListStrategy"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));h.useCallback;function a(a){var b=d("react-compiler-runtime").c(11),e=a.emptyStateContent,f=a.extraViewProps,g=a.nullstateContent,h=a.scrollableXStyle,j=a.viewItemStrategyRenderer,k=a.viewListStrategyRenderer;a=a.viewXStyle;var l=c("useCometInternalTypeaheadState")();l=l.highlightedEntry;var m=c("useCometTypeaheadKeyboardForScrollableArea")(l);b[0]!==e||b[1]!==f||b[2]!==g||b[3]!==j||b[4]!==k||b[5]!==a?(l={emptyStateContent:e,extraViewProps:f,nullstateContent:g,viewItemStrategyRenderer:j,viewListStrategyRenderer:k,viewXStyle:a},b[0]=e,b[1]=f,b[2]=g,b[3]=j,b[4]=k,b[5]=a,b[6]=l):l=b[6];var n=c("useCometTypeaheadViewListStrategy")(l);b[7]!==n||b[8]!==m||b[9]!==h?(e=function(a){return i.jsx(c("CometScrollableArea.react"),{horizontal:!1,ref:m,xstyle:h,children:i.jsx(n,babelHelpers["extends"]({},a))})},b[7]=n,b[8]=m,b[9]=h,b[10]=e):e=b[10];return e}g["default"]=a}),98);
__d("useProfileSwitcherEngagementClickCallback",["FBLogger","ProfileSwitcherAnalyticsEventFalcoEvent","emptyFunction","react","requireDeferred"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||d("react");var i=b.useCallback,j=b.useMemo,k=c("requireDeferred")("ProfileEngagementFalcoEvent").__setRef("useProfileSwitcherEngagementClickCallback");function a(a,b){var d,e=j(function(){return babelHelpers["extends"]({profile_event_type:"click",profile_product_bucket:"unknown",profile_surface:"unknown"},a)},[a]);(a==null?void 0:a.profile_product_bucket)==null&&c("FBLogger")("profile_comet").mustfix("profile_product_bucket is a required field for profile engagement logging");(a==null?void 0:a.profile_surface)==null&&c("FBLogger")("profile_comet").mustfix("profile_surface is a required field for profile engagement logging");var f=c("emptyFunction");(a==null||(d=a.event_metadata)==null?void 0:d.entry_point)==="inline_profile_switcher"&&(f=function(){c("ProfileSwitcherAnalyticsEventFalcoEvent").log(function(){return{event:"actor_profile_photo_switch_select_profile"}})});return i(function(a){k.onReady(function(a){a=a.log;a(function(){return e})}),b&&b(a),f&&f()},[b,e])}g["default"]=a}),98);